apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testnodejs0128a
  janus-idp.io/tekton: testnodejs0128a
  backstage.io/kubernetes-id: testnodejs0128a
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testnodejs0128a
resources:
- deployment.yaml
- route.yaml
- service.yaml
